"""
Supervisor agent: turns a raw user request into a validated ExecutionPlan,
and later synthesizes specialist outputs into the final deliverable.
"""
from __future__ import annotations

from typing import Callable, Optional

from src.schemas.models import ExecutionPlan, SpecialistResult

# prompt needs to instruct the model to:
#   - break the request into subtasks, each assigned to one specialist
#     (name the four specialists explicitly using enum values)
#   - note dependencies between subtasks (e.g. writing usually needs
#     research + analysis done first)
#   - be conservative with `confidence` if the request is vague/open-ended
#   - use {memories} and {request} as format placeholders

PLANNING_PROMPT_TEMPLATE = """
You are the Supervisor Agent in a multi-agent system. Your job is to break down the user's request into a structured ExecutionPlan.

You MUST produce a JSON object that strictly matches the ExecutionPlan schema:
- task_id: auto-generated by the system (the model may leave this blank)
- original_request: the user's request (the system will overwrite this)
- subtasks: a list of SubTask objects
- confidence: a float between 0 and 1
- rationale: a short explanation of your planning decisions


Each SubTask MUST include:
- id: auto-generated (the model may leave this blank)
- description: what the specialist should do
- assigned_specialist: one of the following EXACT values:
    - researcher
    - data_analysis
    - writer
    - code_execution
- required_inputs: list of subtask IDs this one depends on (may be empty)
- depends_on: list of subtask IDs this one depends on (may be empty)
- expected_output_format: a short description of the desired output format
-estimated_complexity: one of : low, medium, high

Planning rules:
1. Break the request into clear subtasks.
2. Assign each subtask to exactly ONE specialist.
3. Use dependencies to enforce correct ordering:
   - writer usually depends on researcher and data_analysis
   - data_analysis usually depends on researcher
   - code_execution depends on whatever produces the code or instructions
4. Use memories when relevant to improve planning.
5. If the request is vague or open-ended, lower the confidence score.
6. Keep subtasks concise and actionable.

Memories:
{memories}

User Request:
{request}

Now produce the ExecutionPlan JSON.

"""


class SupervisorAgent:
    def __init__(self, llm, memory_query_fn: Optional[Callable[[str], list[str]]] = None):
        self.llm = llm
        self.memory_query_fn = memory_query_fn or (lambda request: [])
        

    def create_plan(self, request: str) -> ExecutionPlan:
        memories = self.memory_query_fn(request)
        prompt = PLANNING_PROMPT_TEMPLATE.format(
            memories="\n".join(f"- {m}" for m in memories) or "(none yet)",
            request=request,
        )
        structured_llm = self.llm.with_structured_output(ExecutionPlan)
        plan = structured_llm.invoke(prompt)
        plan = plan.model_copy(update={"original_request": request})
        #    -- overwrite this yourself, don't trust the model's echo.
        #    You already saw exactly this bug with MockLLM in testing --
        #    real models can do the same thing.
        return plan

    def synthesize(self, plan: ExecutionPlan, results: dict[str, SpecialistResult]) -> str:
        sections = []
        for sub in plan.subtasks:
            result = results.get(sub.id)
            if not result:
                continue 

            sections.append(
                f"### {result.specialist.value} ({result.subtask_id})\n{result.output}"
            )

        body = "\n\n".join(sections)
        return f"# Final Output for Request: {plan.original_request}\n\n{body}"